"""Tools for tailoring LaTeX resumes to a job description."""

import re
import shutil
import subprocess
from pathlib import Path

from src.config.settings import REPO_ROOT

DEFAULT_RESUME_PATH = "dataset/resume.tex"
MAX_INPUT_BYTES = 1_000_000

BLOCK_RE = re.compile(
    r"<{7}\s*SEARCH\s*\r?\n(.*?)\r?\n={7}\s*\r?\n(.*?)\r?\n>{7}\s*REPLACE",
    re.DOTALL,
)


def _resolve_path(file_path: str, allowed_suffixes: set[str]) -> Path:
    """Resolve a user path and keep file access inside the repository."""
    candidate = Path(file_path).expanduser()
    if not candidate.is_absolute():
        candidate = REPO_ROOT / candidate
    candidate = candidate.resolve()

    try:
        candidate.relative_to(REPO_ROOT.resolve())
    except ValueError as exc:
        raise ValueError("Resume files must be inside the Wingman project directory.") from exc

    if candidate.suffix.lower() not in allowed_suffixes:
        suffixes = ", ".join(sorted(allowed_suffixes))
        raise ValueError(f"Expected one of these file types: {suffixes}")
    return candidate


def _read_input(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"File not found: {path}")
    if path.stat().st_size > MAX_INPUT_BYTES:
        raise ValueError(f"Input file is larger than {MAX_INPUT_BYTES} bytes: {path}")
    return path.read_text(encoding="utf-8")


def read_resume(resume_path: str = DEFAULT_RESUME_PATH) -> dict:
    """Read the LaTeX resume source file and return its content.

    Args:
        resume_path: Path to the .tex resume file. Defaults to dataset/resume.tex.

    Returns:
        A dict with 'status' and 'content' (the raw LaTeX text).
    """
    try:
        source_path = _resolve_path(resume_path, {".tex"})
        content = _read_input(source_path)
        return {"status": "success", "content": content, "source_path": str(source_path)}
    except Exception as exc:
        return {"status": "error", "message": str(exc)}


def apply_patches(patch_text: str, resume_path: str = DEFAULT_RESUME_PATH, output_path: str = "") -> dict:
    """Apply SEARCH/REPLACE patch blocks generated by the agent to the resume and save it.

    Args:
        patch_text: The raw SEARCH/REPLACE block text produced by the agent.
        resume_path: Source .tex resume path. Defaults to dataset/resume.tex.
        output_path: Optional output .tex path. Defaults to <stem>_tailored.tex beside the source.

    Returns:
        A status dict with output path, patch counts, and any failed patches.
    """
    try:
        source_path = _resolve_path(resume_path, {".tex"})
        if output_path:
            destination = _resolve_path(output_path, {".tex"})
        else:
            destination = source_path.with_name(f"{source_path.stem}_tailored.tex")

        if destination == source_path:
            raise ValueError("Output path must not overwrite the source resume.")

        original = _read_input(source_path)
        blocks = BLOCK_RE.findall(patch_text)
        if not blocks:
            raise ValueError("No SEARCH/REPLACE blocks found in patch text.")

        result = original
        applied = 0
        failed: list[str] = []
        for search, replacement in blocks:
            count = result.count(search)
            if count == 0:
                failed.append(f"[NOT FOUND] {search[:80]}")
                continue
            if count > 1:
                failed.append(f"[AMBIGUOUS, {count} matches] {search[:80]}")
                continue
            result = result.replace(search, replacement, 1)
            applied += 1

        if applied == 0:
            raise ValueError("No patches matched the source resume.")
        if result.count("{") != result.count("}"):
            raise ValueError("Tailored LaTeX has mismatched braces; output was not saved.")

        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(result, encoding="utf-8")

        return {
            "status": "success",
            "output_path": str(destination),
            "patches_applied": applied,
            "patches_total": len(blocks),
            "failed_patches": failed,
        }
    except Exception as exc:
        return {"status": "error", "message": str(exc)}


def compile_resume_to_pdf(tex_path: str, output_directory: str = "") -> dict:
    """Compile a tailored LaTeX resume to PDF with two pdflatex passes.

    Args:
        tex_path: Path to a .tex file inside the project directory.
        output_directory: Optional output directory inside the project.

    Returns:
        A status dictionary containing the generated PDF path.
    """
    try:
        source_path = _resolve_path(tex_path, {".tex"})
        if not source_path.is_file():
            raise FileNotFoundError(f"File not found: {source_path}")
        if shutil.which("pdflatex") is None:
            raise RuntimeError(
                "pdflatex was not found. Install MiKTeX or another LaTeX distribution."
            )

        if output_directory:
            output_dir = _resolve_path(
                str(Path(output_directory) / "placeholder.pdf"), {".pdf"}
            ).parent
        else:
            output_dir = source_path.parent
        output_dir.mkdir(parents=True, exist_ok=True)

        for pass_number in range(1, 3):
            result = subprocess.run(
                [
                    "pdflatex",
                    "-interaction=nonstopmode",
                    "-output-directory",
                    str(output_dir),
                    source_path.name,
                ],
                cwd=source_path.parent,
                capture_output=True,
                text=True,
                timeout=120,
                check=False,
            )
            if result.returncode != 0:
                log_tail = result.stdout[-3000:]
                raise RuntimeError(
                    f"pdflatex failed on pass {pass_number}:\n{log_tail}"
                )

        pdf_path = output_dir / f"{source_path.stem}.pdf"
        if not pdf_path.is_file():
            raise RuntimeError("pdflatex succeeded but did not create a PDF.")

        for suffix in (".aux", ".log", ".out"):
            auxiliary = output_dir / f"{source_path.stem}{suffix}"
            auxiliary.unlink(missing_ok=True)

        return {
            "status": "success",
            "pdf_path": str(pdf_path),
            "attachment_marker": f"[[SEND_FILE:{pdf_path}]]",
        }
    except Exception as exc:
        return {"status": "error", "message": str(exc)}
